#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "yclean ${1} using "${BASH_SOURCE[0]}

#cd $SCRIPT_DIR

YHOME=`cat ${HOME}/.yhome.txt`

if [ ${#YHOME} = 0 ]
then echo "YHOME=${YHOME} is not set";
exit;
fi

# rm -f ${YHOME}/dbg/yosoy.conf

cd ${YHOME}/build

make clean

cd ${YHOME}

find . -mount -name "Makefile" -exec rm -f '{}' \;
find . -mount -name "*.log" -exec rm -f '{}' \;
find . -mount -name "*~" -exec rm -f '{}' \;

echo "Finished yclean ----------------------------- "

cd ${CURR_DIR}