#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "ysave ${1} using "${BASH_SOURCE[0]}

#cd $SCRIPT_DIR

YHOME=`cat ${HOME}/.yhome.txt`

if [ ${#YHOME} = 0 ]
then echo "YHOME=${YHOME} is not set";
exit;
fi

cd ${YHOME}
# make clean

${YHOME}/scripts/yclean_sh
rm -rf ${YHOME}/bin
mkdir ${YHOME}/bin
mkdir ${YHOME}/bin/obj

BASE=`basename ${YHOME}`
cd ${YHOME}/..
PNT_YHOME=`pwd`
BASCURR=`basename ${PNT_YHOME}`

if [ ${BASCURR} != "tmp" ]
then echo "Not in a tmp dir !!!";
exit;
fi

echo "CHECKING RAM LOCATION..."
MNT=`sudo df -a | grep none | grep ${PNT_YHOME}`

if [ ${#MNT} == 0 ]
then echo "NOT SAVING IN A RAMFS DIR";
exit;
fi

PREFIX=`date +"%Y_%m_%d_%Hh_%Mm_"`
TGZF=${PNT_YHOME}/sv.tgz
TARGET=${PNT_YHOME}/../${PREFIX}${BASE}.txt

tar cvzf ${TGZF} ./${BASE}

# ENcrypt from directory with file vision
cd ${YHOME}/..

echo "ENCRYPTING..."
echo "CURRENT DIRECTORY="`pwd`
cry3 ${TGZF} -x
mv ${TGZF}.encry.txt ${TARGET}
rm ${TGZF}

echo "Saved ${TARGET}"

